In [1]:
import numpy as np
x=np.array([1,2,3])
print(x)
data=np.array([1.5,-2,3])
print(data,"and it's type is",type(data))

[1 2 3]
[ 1.5 -2.   3. ] and it's type is <class 'numpy.ndarray'>


In [2]:
data=np.array([[1.5,-2,3],['Hello',4.7,'ITER']])
print(data)

[['1.5' '-2' '3']
 ['Hello' '4.7' 'ITER']]


In [4]:
data.ndim

2

In [5]:
data.shape

(2, 3)

In [7]:
y=np.ones(7)
y

array([1., 1., 1., 1., 1., 1., 1.])

In [8]:
x=np.zeros(7)
x

array([0., 0., 0., 0., 0., 0., 0.])

In [10]:
arr1=np.random.randint(1,100,size=10)   
arr2=np.random.randint(1,100,size=10) 
print("Array 1:",arr1)
print("Array 2:",arr2)
greater=arr1>arr2
less=arr1<arr2
equal=arr1=arr2
print("Greater than:",greater)
print("Less than:",less)
print("Equal:",equal)
count=np.sum(greater)
print(count)

Array 1: [44 57  3 31  6 46 26 90 91 65]
Array 2: [74 33 55 13 95 25 66  2 44 30]
Greater than: [False  True False  True False  True False  True  True  True]
Less than: [ True False  True False  True False  True False False False]
Equal: [74 33 55 13 95 25 66  2 44 30]
6


In [14]:
marks_list=[12,34,56,78,90,21,43,65,87,91]
marks_array=np.array(marks_list)
average=np.mean(marks_array)
print("Average marks:",average)
above_avg=marks_array[marks_array > average]
print("Students who scored above average:",above_avg)

Average marks: 57.7
Students who scored above average: [78 90 65 87 91]


In [21]:
# matrix=np.array([1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16])   
arr=np.arange(1,17).reshape(4,4)
print("\n Original 4*4 \n",arr)
sec_row=arr[1,:]
print("\n Second row",sec_row)
Third_col=arr[:,2]
print("\n Third Col",Third_col)
sub_matrix=arr[2:4,2:4]
print("\n 2x2 sub-matrix from bottom right corner:\n",sub_matrix)


 Original 4*4 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

 Second row [5 6 7 8]

 Second row [ 3  7 11 15]

 2x2 sub-matrix from bottom right corner:
 [[11 12]
 [15 16]]


In [2]:
import numpy as np

arr=np.arange(1,13).reshape(3,4)
print("Original Array:\n",arr)
print("reshaped array:\n",arr.reshape(4,3))
print("reshaped array:\n",arr.ravel())
      


Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
reshaped array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
reshaped array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [8]:
import numpy as np
val=np.random.randint(1,7,1000)
# print(val)
dics={i:np.sum(val==i) for i in range(1,7)}
print(dics)

{1: 150, 2: 160, 3: 178, 4: 191, 5: 157, 6: 164}


In [9]:
#Q5
import numpy as np
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(1,10).reshape(3,3)
print(np.matmul(arr1,arr2))

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [12]:
import numpy as np
arr1=np.arange(1,10).reshape(3,3)
det=np.linalg.det(arr1)
inv=np.linalg.inv(arr1)
idcheck=np.dot(arr1,inv)
print(det)
print(inv)
print(idcheck)

6.66133814775094e-16
[[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]
[[ 0.  0.  0.]
 [-4.  0. -4.]
 [ 0.  0.  0.]]
